services:
  green-detective-localstack-s3:
    container_name: green-detective-localstack-s3
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack_data
    volumes:
      - ./s3_docker_mount:/tmp/localstack_data
    ports:
      - 4566:4566
    networks:
      - green-detective-localstack-s3
  green-detective-s3-cli:
    container_name: green-detective-s3-cli
    image: amazon/aws-cli
    depends_on:
      - green-detective-localstack-s3
    volumes:
      - ./docker/aws:/root/.aws
    entrypoint: "/root/.aws/create_s3_buckets.sh"
    networks:
      - green-detective-localstack-s3
  green-detective-postgresdb:
    container_name: green-detective-postgresdb
    image: ankane/pgvector:latest
    command: postgres -c 'max_connections=300'
    shm_size: 256m
    volumes:
      - ./docker/database_mount/pgsql_docker_mount:/var/lib/postgresql/data
      - ./docker/database_mount/pgsql_docker_mount_restore:/tmp/restore
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 9500:5432
    networks:
      - green-detective-postgresdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  green-detective-redis:
    container_name: green-detective-redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 9379:6379
    networks:
      - green-detective-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  green-detective-mailhog:
    container_name: green-detective-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    networks:
      - green-detective-service-api
networks:
  green-detective-postgresdb:
    name: green-detective-postgresdb
    driver: bridge
  green-detective-redis:
    name: green-detective-redis
    driver: bridge
  green-detective-localstack-s3:
    name: green-detective-localstack-s3
    driver: bridge
