# Generated by Django 5.0.6 on 2024-06-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
