# Generated by Django 5.0.6 on 2025-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0002_vector_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='processing',
        ),
        migrations.AddField(
            model_name='report',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
