# Generated by Django 5.0.6 on 2024-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0002_alter_company_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_uuid',
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
