# Generated by Django 5.0.6 on 2025-01-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0002_payment_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='reports_generated',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='detective.business'),
        ),
    ]
