# Generated by Django 5.0.6 on 2025-01-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0003_remove_report_processing_report_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='defunct',
            field=models.BooleanField(default=False),
        ),
    ]
