# Generated by Django 5.0.6 on 2024-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0003_remove_report_user_uuid_report_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
