# Generated by Django 5.0.6 on 2025-01-30 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0004_alter_userprofile_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityGlossary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the glossary term', primary_key=True, serialize=False)),
                ('term', models.CharField(help_text='The sustainability term or phrase', max_length=255, unique=True)),
                ('definition', models.TextField(help_text='Detailed definition of the term')),
                ('defunct', models.BooleanField(default=False, help_text='Mark if this term is no longer relevant or should be excluded from analysis')),
                ('source', models.CharField(help_text='Source of the term definition', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Category or grouping for the term', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the term was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the term was last updated')),
            ],
            options={
                'verbose_name': 'Sustainability Glossary',
                'verbose_name_plural': 'Sustainability Glossaries',
                'ordering': ['term'],
            },
        ),
    ]
