# Generated by Django 5.0.6 on 2025-01-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0005_sustainabilityglossary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilityglossary',
            name='definition',
        ),
        migrations.AddField(
            model_name='sustainabilityglossary',
            name='context',
            field=models.TextField(blank=True, help_text='Additional context for the term', null=True),
        ),
    ]
