# Generated by Django 5.0.6 on 2024-06-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0005_alter_report_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processing',
            field=models.BooleanField(default=True),
        ),
    ]
