# Generated by Django 5.0.6 on 2024-07-08 21:25

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0006_report_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='company_uuid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staging',
            old_name='company_uuid',
            new_name='company',
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='detective.company'),
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='staging',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='detective.staging'),
        ),
        migrations.AddField(
            model_name='report',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2048), default=list, size=20),
        ),
        migrations.AddField(
            model_name='staging',
            name='processed',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=255),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_oa_id', models.CharField(max_length=255, unique=True)),
                ('thread_oa_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('requires_action', 'Requires Action'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('completed', 'Completed'), ('expired', 'Expired')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('staging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detective.staging')),
            ],
        ),
    ]
