# Generated by Django 5.0.6 on 2025-01-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0006_remove_sustainabilityglossary_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilityglossary',
            name='definition',
            field=models.TextField(default='', help_text='Detailed definition of the term'),
        ),
    ]
