# Generated by Django 5.0.6 on 2025-01-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0006_business_emailverificationtoken_invitecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstatistics',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='justification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
