# Generated by Django 5.0.6 on 2025-01-30 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0007_sustainabilityglossary_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2048), blank=True, default=list, null=True, size=20),
        ),
    ]
