# Generated by Django 5.0.6 on 2024-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0007_rename_company_uuid_report_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstatistics',
            name='url',
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='claim',
            field=models.TextField(default=None),
        ),
    ]
