# Generated by Django 5.0.6 on 2025-01-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0007_rawstatistics_category_rawstatistics_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstatistics',
            name='comparison_analysis',
            field=models.JSONField(blank=True, help_text='Raw JSON response from claim comparison analysis', null=True),
        ),
    ]
