# Generated by Django 5.0.6 on 2024-07-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0008_remove_rawstatistics_url_rawstatistics_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedstatistics',
            old_name='company_uuid',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='rawstatistics',
            name='staging',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='detective.staging'),
        ),
    ]
