# Generated by Django 5.0.6 on 2025-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0008_rawstatistics_comparison_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstatistics',
            name='staging',
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='staging',
            field=models.ManyToManyField(to='detective.staging'),
        ),
    ]
