# Generated by Django 5.0.6 on 2024-07-11 00:10

import custom_storages
import detective.models.report
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0009_rename_company_uuid_processedstatistics_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='s3_url',
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, storage=custom_storages.ReportStorage(), upload_to=detective.models.report.get_upload_path),
        ),
    ]
