# Generated by Django 5.0.6 on 2024-07-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0010_remove_report_s3_url_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='about_summary',
            field=models.TextField(default=''),
        ),
    ]
