# Generated by Django 5.0.6 on 2024-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0011_company_about_raw_company_about_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_url',
            field=models.URLField(default=''),
        ),
    ]
