# Generated by Django 5.0.6 on 2024-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective', '0012_company_about_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staging',
            old_name='raw_html',
            new_name='raw',
        ),
        migrations.AddField(
            model_name='rawstatistics',
            name='processed',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=255),
        ),
    ]
